apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-gen
  template:
    metadata:
      labels:
        app: load-gen
    spec:
      containers:
      - name: load-gen
        image: load-gen:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: TARGET_ADDR
          value: "matching-svc:50057"
